### PR TITLE
Add base JavaScript style guide

### PR DESCRIPTION
**Pull request by 3lvis**
This is mainly a copy of AirBnb's style guide. It's intended to serve as a base, discussions might be better if they come in the form of a PR instead of just comments on this one.

https://github.com/airbnb/javascript

### CODE REVIEW

**Comment by jgorset** [comment]
Yup. I guess the question here is really "do we want a style guide", and we definitely do.

**Comment by jgorset** [comment]
:cake: for you, @3lvis!

**Comment by 3lvis** [comment]
Thanks!

bill_murray_gif_9

**Comment by fespinoza** [comment]
:+1:

**Pull request merged**
